CREATE DATABASE IF NOT EXISTS cuestionario;
USE cuestionario;

CREATE TABLE IF NOT EXISTS question (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pregunta TEXT NOT NULL,
    opcionA VARCHAR(255) NOT NULL,
    opcionB VARCHAR(255) NOT NULL,
    opcionC VARCHAR(255) NOT NULL,
    opcionD VARCHAR(255) NOT NULL,
    respuesta CHAR(1) NOT NULL,
    teoria TEXT
);

INSERT INTO question (pregunta, opcionA, opcionB, opcionC, opcionD, respuesta, teoria) VALUES
('De acuerdo con el artículo 64 de la Constitución Española de 1978 (en adelante CE), los actos del Rey, excepto la propuesta y el nombramiento del Presidente del Gobierno, y la disolución de las Cámaras prevista en el artículo 99, serán refrendados por:', 'Los Presidentes del Congreso y el Senado.', 'Los Ministros o los Secretarios de Estado en función de la materia.', 'El Presidente del Gobierno y, en su caso, por los Presidentes del Congreso y el Senado.', 'El Presidente del Gobierno y, en su caso, por los Ministros competentes.', 'd', 'Artículo 64 de la CE.'),
('La suspensión de los derechos y libertades se encuentra regulada en la CE en:', 'En el Capítulo III del Título I.', 'En sus artículos 52 y 53.', 'En el artículo 58.', 'En el Capítulo V del Título I.', 'd', 'Artículo 55 de la CE.'),
('Según el artículo 68 de la CE, ¿cuál es la circunscripción electoral en nuestro sistema electoral?', 'La provincia.', 'El municipio.', 'La Comunidad Autónoma.', 'Distrito Municipal.', 'a', 'Artículo 68 de la CE.'),
('Según el artículo 18 de la ley 50/1997, de 27 de noviembre, del Gobierno que regula el funcionamiento del Consejo de Ministros, ¿quién actúa como Secretario de este órgano colegiado?', 'El Vicepresidente Primero.', 'El Ministro portavoz del Gobierno.', 'El Ministro de la Presidencia.', 'El Ministro de Justicia.', 'c', 'Artículo 18 de la Ley 50/1997.'),
('De acuerdo con el artículo 78 de la CE, expirado el mandato de las Cortes Generales o en caso de disolución de las mismas, las Diputaciones Permanentes seguirán ejerciendo sus funciones hasta:', 'La celebración de las elecciones.', 'La proclamación de los resultados electorales definitivos.', 'La elección de los nuevos presidentes de cada una de las Cámaras de las Cortes Generales.', 'La constitución de las nuevas Cortes Generales.', 'd', 'Artículo 78 de la CE.'),
('Según establece el artículo 24 de la Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno, el plazo máximo para resolver y notificar la resolución de una reclamación ante el Consejo de Transparencia y Buen Gobierno será de:', 'Un mes, transcurrido el cual, la reclamación se entenderá estimada.', 'Un mes, transcurrido el cual, la reclamación se entenderá desestimada.', 'Tres meses, transcurrido el cual, la reclamación se entenderá estimada.', 'Tres meses, transcurrido el cual, la reclamación se entenderá desestimada.', 'd', 'Artículo 24 de la Ley 19/2013.'),
('Señale cuál de los siguientes NO es un compromiso del IV Plan de Gobierno Abierto de España:', 'Participación de los jóvenes en políticas públicas.', 'Protección de denunciantes.', 'Huella normativa.', 'Reforma del marco regulatorio.', 'd', 'IV Plan de Gobierno Abierto de España.'),
('Conforme establece el artículo 18 de la Ley 53/1984, de 26 de diciembre, de Incompatibilidades del personal al servicio de las Administraciones Públicas, todas las resoluciones de compatibilidad para desempeñar un segundo puesto o actividad en el sector público o el ejercicio de actividades privadas se inscribirán:', 'En el Registro Central de Personal.', 'En la Oficina de Conflicto de Intereses.', 'En la Unidad de Personal del Ministerio u Organismo correspondiente.', 'En los Registros de Personal correspondientes.', 'a', 'Artículo 18 de la Ley 53/1984.'),
('De acuerdo con el artículo 30 de la Ley 39/2006, de 14 de diciembre, de Promoción de la Autonomía Personal y Atención a las personas en situación de dependencia, el grado de dependencia será revisable:', 'A instancia del interesado.', 'A instancia de los representantes del interesado.', 'De oficio por las Administraciones Públicas competentes.', 'Todas las respuestas anteriores son correctas.', 'd', 'Artículo 30 de la Ley 39/2006.'),
('Conforme el artículo 49 de la Ley Orgánica 3/2007, de 22 de marzo, para la igualdad efectiva de mujeres y hombres, para impulsar la adopción voluntaria de planes de igualdad, el Gobierno establecerá:', 'Medidas de acción positiva, especialmente dirigidas a las pequeñas y las medianas empresas.', 'Medidas de fomento, especialmente dirigidas a las empresas de 50 o más trabajadores.', 'Medidas de fomento, especialmente dirigidas a las pequeñas y las medianas empresas.', 'Medidas de acción positiva, dirigidas a cualquier empresa, sea de capital público o privado.', 'c', 'Artículo 49 de la Ley Orgánica 3/2007.'),
('Con carácter general el documento nacional de identidad tendrá un período de validez, a contar desde la fecha de la expedición o de cada una de sus renovaciones, de:', 'Dos años cuando el solicitante no haya cumplido los cinco años de edad.', 'Cuatro años, cuando el titular haya cumplido los cinco años de edad y no haya alcanzado los treinta al momento de la expedición o renovación.', 'Nueve años, cuando el titular haya cumplido los treinta y no haya alcanzado los setenta.', 'Permanente cuando el titular haya cumplido los sesenta años.', 'a', 'Ley del Documento Nacional de Identidad.'),
('De acuerdo con el artículo 4 de la Ley 6/2020, de 11 de noviembre, reguladora de determinados aspectos de los servicios electrónicos de confianza, el periodo de vigencia de los certificados cualificados:', 'No será superior a 5 años.', 'No será superior a 3 años.', 'Es ilimitado.', 'No será superior a 6 años.', 'a', 'Artículo 4 de la Ley 6/2020.'),
('Indique según el título X de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, ¿cuál de los siguientes NO es un derecho digital?', 'Derecho al testamento digital.', 'Derecho al olvido en servicios de redes sociales y servicios equivalentes.', 'Derecho a la desconexión digital en el ámbito laboral.', 'Derecho a la igualdad y a la no discriminación en el entorno digital.', 'd', 'Título X de la Ley Orgánica 3/2018.'),
('Según establece el artículo 34 de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, los responsables y encargados de tratamiento comunicarán a la Agencia Española de Protección de Datos, las designaciones, nombramientos y ceses de los delegados de protección de datos en el plazo de:', '10 días.', '15 días.', '1 mes.', '3 meses.', 'b', 'Artículo 34 de la Ley Orgánica 3/2018.'),
('Según el Real Decreto 311/2022, de 3 de mayo, por el que se regula el Esquema Nacional de Seguridad, ¿cuál de las siguientes medidas de seguridad afecta a la dimensión de Confidencialidad?', 'Bloqueo de puesto de trabajo.', 'Firma electrónica.', 'Registro de la actividad.', 'Criptografía.', 'd', 'Real Decreto 311/2022.'),
('Señale la respuesta correcta sobre lo que establece la Norma Técnica de Interoperabilidad de Protocolos de Intermediación de Datos:', 'Las tecnologías utilizadas para los intercambios se implementarán en base a estándares según lo establecido en la Norma Técnica de Interoperabilidad de Catálogo de estándares.', 'De forma general en servicios de intercambio se utilizará la versión 2.0 del protocolo SCSP (Sustitución de Certificados en Soporte Papel).', 'Emisores y Requirentes no mantendrán trazabilidad de los intercambios de datos producidos.', 'Los intercambios de información se podrán implementar a través de servicios web.', 'a', 'Norma Técnica de Interoperabilidad.'),
('Señale qué afirmación es correcta con respecto a las soluciones de Ciberseguridad proporcionadas por el Centro Criptológico Nacional (CCN):', 'CLARA, protección y trazabilidad del dato.', 'ELENA, Simulador de Técnicas de Cibervigilancia.', 'GLORIA, Gestión de eventos e información de seguridad.', 'MONICA, Gestor de logs para responder ante incidentes y amenazas.', 'a', 'Centro Criptológico Nacional.'),
('Señale la respuesta correcta referente a los servicios comunes en materia de administración electrónica:', 'SERVINOMINA realiza la gestión completa de las fases de nómina: cálculo, contabilidad y pago.', 'CIRCAB poderosa herramienta de trabajo en grupo para intercambio de información y trabajo colaborativo.', 'eVISOR permite a un empleado público la consulta de sus nóminas correspondientes a los cinco últimos años.', 'ENVIA es una aplicación que hace posible el envío de ficheros de gran volumen entre usuarios.', 'c', 'Servicios comunes en administración electrónica.'),
('La CE regula la institución del Defensor del Pueblo como:', 'Alto comisionado del Congreso de los Diputados.', 'Alto comisionado de las Cortes Generales.', 'Alto comisionado del Poder judicial.', 'Alto comisionado del Gobierno de la nación.', 'b', 'Artículo 54 de la CE.'),
('¿Qué es WCAG?', 'Unas pautas de accesibilidad de contenidos web promovidas por el W3C.', 'Una librería de Java EE para la creación de aplicaciones web creada por Oracle.', 'Un componente del ecosistema Hadoop para el manejo de Big Data.', 'Un framework javascript especialmente indicado para trabajar con bases de datos no relacionales.', 'a', 'WCAG (Web Content Accessibility Guidelines).');

USE cuestionario;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO users (username, password) VALUES
('user1', '$2a$10$7zB1Gc8htRz2ekHtVsKrCeo.eC/kmsScGF9wDGLB6z4QmyAv1h1iS'),
('user2', '$2a$10$WCL8Q/z9nZdf1mZROgxSUOf9nBvJ4zPPkXtI.AqHbuzOjj8rAG/9q'),
('user3', '$2a$10$FikmOQsWQX9XwnY8OY/fd.9D1gW/Fu7OFPdIcHC.k3xeT/tKAKOuq'),
('user4', '$2a$10$ptQzD1g3/.gUOn8W9FR2Ue8J2OV8RJW5qBdGVpP.kg2t7XJlO7F7y'),
('user5', '$2a$10$dd8/rTtFszG0TE8mfbfwFO.D/YwYx9GBNtpIdPCY5Rxu0lgFGJMXu');

-- user1: user1password
-- user2: user2password
-- user3: user3password
-- user4: user4password
-- user5: user5password

ALTER USER 'userCe'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Z1234ori=';

FLUSH PRIVILEGES;

UPDATE question
SET teoria = 'El Artículo 4 de la Ley 6/2020, de 11 de noviembre, reguladora de determinados aspectos de los servicios electrónicos de confianza, establece el "Periodo de vigencia de los certificados cualificados". A continuación, te proporciono el contenido relevante del artículo:

Artículo 4. Periodo de vigencia de los certificados cualificados.
Los certificados cualificados no tendrán un periodo de vigencia superior a cinco años.

Los prestadores de servicios de certificación deberán informar al titular del certificado cualificado sobre la fecha de expiración del certificado y sobre la posibilidad de renovarlo antes de que expire, de acuerdo con lo previsto en las normas que regulan dichos certificados.

El certificado cualificado caducará cuando finalice su periodo de vigencia, a menos que haya sido revocado con anterioridad.

Este artículo establece límites claros sobre el tiempo durante el cual los certificados cualificados son válidos, subrayando que no deben tener una vigencia superior a cinco años, e incluye disposiciones sobre la renovación y caducidad de estos certificados.'
WHERE id = 12;

USE cuestionario;

-- legales
INSERT INTO question (pregunta, opcionA, opcionB, opcionC, opcionD, respuesta, teoria) VALUES
('De acuerdo con el artículo 64 de la Constitución Española de 1978 (en adelante CE), los actos del Rey, excepto la propuesta y el nombramiento del Presidente del Gobierno, y la disolución de las Cámaras prevista en el artículo 99, serán refrendados por:', 'Los Presidentes del Congreso y el Senado.', 'Los Ministros o los Secretarios de Estado en función de la materia.', 'El Presidente del Gobierno y, en su caso, por los Presidentes del Congreso y el Senado.', 'El Presidente del Gobierno y, en su caso, por los Ministros competentes.', 'd', 'Artículo 64 de la CE.'),
('La suspensión de los derechos y libertades se encuentra regulada en la CE en:', 'En el Capítulo III del Título I.', 'En sus artículos 52 y 53.', 'En el artículo 58.', 'En el Capítulo V del Título I.', 'd', 'Artículo 55 de la CE.'),
('Según el artículo 68 de la CE, ¿cuál es la circunscripción electoral en nuestro sistema electoral?', 'La provincia.', 'El municipio.', 'La Comunidad Autónoma.', 'Distrito Municipal.', 'a', 'Artículo 68 de la CE.'),
('Según el artículo 18 de la ley 50/1997, de 27 de noviembre, del Gobierno que regula el funcionamiento del Consejo de Ministros, ¿quién actúa como Secretario de este órgano colegiado?', 'El Vicepresidente Primero.', 'El Ministro portavoz del Gobierno.', 'El Ministro de la Presidencia.', 'El Ministro de Justicia.', 'c', 'Artículo 18 de la Ley 50/1997.'),
('De acuerdo con el artículo 78 de la CE, expirado el mandato de las Cortes Generales o en caso de disolución de las mismas, las Diputaciones Permanentes seguirán ejerciendo sus funciones hasta:', 'La celebración de las elecciones.', 'La proclamación de los resultados electorales definitivos.', 'La elección de los nuevos presidentes de cada una de las Cámaras de las Cortes Generales.', 'La constitución de las nuevas Cortes Generales.', 'd', 'Artículo 78 de la CE.'),
('Según establece el artículo 24 de la Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno, el plazo máximo para resolver y notificar la resolución de una reclamación ante el Consejo de Transparencia y Buen Gobierno será de:', 'Un mes, transcurrido el cual, la reclamación se entenderá estimada.', 'Un mes, transcurrido el cual, la reclamación se entenderá desestimada.', 'Tres meses, transcurrido el cual, la reclamación se entenderá estimada.', 'Tres meses, transcurrido el cual, la reclamación se entenderá desestimada.', 'd', 'Artículo 24 de la Ley 19/2013.'),
('Señale cuál de los siguientes NO es un compromiso del IV Plan de Gobierno Abierto de España:', 'Participación de los jóvenes en políticas públicas.', 'Protección de denunciantes.', 'Huella normativa.', 'Reforma del marco regulatorio.', 'd', 'IV Plan de Gobierno Abierto de España.'),
('Conforme establece el artículo 18 de la Ley 53/1984, de 26 de diciembre, de Incompatibilidades del personal al servicio de las Administraciones Públicas, todas las resoluciones de compatibilidad para desempeñar un segundo puesto o actividad en el sector público o el ejercicio de actividades privadas se inscribirán:', 'En el Registro Central de Personal.', 'En la Oficina de Conflicto de Intereses.', 'En la Unidad de Personal del Ministerio u Organismo correspondiente.', 'En los Registros de Personal correspondientes.', 'a', 'Artículo 18 de la Ley 53/1984.'),
('De acuerdo con el artículo 30 de la Ley 39/2006, de 14 de diciembre, de Promoción de la Autonomía Personal y Atención a las personas en situación de dependencia, el grado de dependencia será revisable:', 'A instancia del interesado.', 'A instancia de los representantes del interesado.', 'De oficio por las Administraciones Públicas competentes.', 'Todas las respuestas anteriores son correctas.', 'd', 'Artículo 30 de la Ley 39/2006.'),
('Conforme el artículo 49 de la Ley Orgánica 3/2007, de 22 de marzo, para la igualdad efectiva de mujeres y hombres, para impulsar la adopción voluntaria de planes de igualdad, el Gobierno establecerá:', 'Medidas de acción positiva, especialmente dirigidas a las pequeñas y las medianas empresas.', 'Medidas de fomento, especialmente dirigidas a las empresas de 50 o más trabajadores.', 'Medidas de fomento, especialmente dirigidas a las pequeñas y las medianas empresas.', 'Medidas de acción positiva, dirigidas a cualquier empresa, sea de capital público o privado.', 'c', 'Artículo 49 de la Ley Orgánica 3/2007.'),
('Con carácter general el documento nacional de identidad tendrá un período de validez, a contar desde la fecha de la expedición o de cada una de sus renovaciones, de:', 'Dos años cuando el solicitante no haya cumplido los cinco años de edad.', 'Cuatro años, cuando el titular haya cumplido los cinco años de edad y no haya alcanzado los treinta al momento de la expedición o renovación.', 'Nueve años, cuando el titular haya cumplido los treinta y no haya alcanzado los setenta.', 'Permanente cuando el titular haya cumplido los sesenta años.', 'a', 'Ley del Documento Nacional de Identidad.'),
('De acuerdo con el artículo 4 de la Ley 6/2020, de 11 de noviembre, reguladora de determinados aspectos de los servicios electrónicos de confianza, el periodo de vigencia de los certificados cualificados:', 'No será superior a 5 años.', 'No será superior a 3 años.', 'Es ilimitado.', 'No será superior a 6 años.', 'a', 'Artículo 4 de la Ley 6/2020.'),
('Indique según el título X de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, ¿cuál de los siguientes NO es un derecho digital?', 'Derecho al testamento digital.', 'Derecho al olvido en servicios de redes sociales y servicios equivalentes.', 'Derecho a la desconexión digital en el ámbito laboral.', 'Derecho a la igualdad y a la no discriminación en el entorno digital.', 'd', 'Título X de la Ley Orgánica 3/2018.'),
('Según establece el artículo 34 de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, los responsables y encargados de tratamiento comunicarán a la Agencia Española de Protección de Datos, las designaciones, nombramientos y ceses de los delegados de protección de datos en el plazo de:', '10 días.', '15 días.', '1 mes.', '3 meses.', 'b', 'Artículo 34 de la Ley Orgánica 3/2018.'),
('Según el Real Decreto 311/2022, de 3 de mayo, por el que se regula el Esquema Nacional de Seguridad, ¿cuál de las siguientes medidas de seguridad afecta a la dimensión de Confidencialidad?', 'Bloqueo de puesto de trabajo.', 'Firma electrónica.', 'Registro de la actividad.', 'Criptografía.', 'd', 'Real Decreto 311/2022.'),
('La CE regula la institución del Defensor del Pueblo como:', 'Alto comisionado del Congreso de los Diputados.', 'Alto comisionado de las Cortes Generales.', 'Alto comisionado del Poder judicial.', 'Alto comisionado del Gobierno de la nación.', 'b', 'Artículo 54 de la CE.'),
('Señale la respuesta correcta sobre lo que establece la Norma Técnica de Interoperabilidad de Protocolos de Intermediación de Datos:', 'Las tecnologías utilizadas para los intercambios se implementarán en base a estándares según lo establecido en la Norma Técnica de Interoperabilidad de Catálogo de estándares.', 'De forma general en servicios de intercambio se utilizará la versión 2.0 del protocolo SCSP (Sustitución de Certificados en Soporte Papel).', 'Emisores y Requirentes no mantendrán trazabilidad de los intercambios de datos producidos.', 'Los intercambios de información se podrán implementar a través de servicios web.', 'a', 'Norma Técnica de Interoperabilidad.'),
('¿Cuál es el órgano que asume las funciones de la Comisión Europea en los Estados Miembros?', 'Parlamento Europeo.', 'Consejo de la Unión Europea.', 'Comisión Europea.', 'Tribunal de Justicia de la Unión Europea.', 'c', 'La Comisión Europea es el órgano que asume las funciones ejecutivas y la aplicación del derecho comunitario.'),
('En relación con la Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno, señale la afirmación correcta:', 'El principio de transparencia es solo aplicable a las administraciones públicas.', 'Los sujetos obligados no deben justificar la denegación del acceso a la información.', 'El acceso a la información es un derecho fundamental.', 'Los sujetos obligados deben publicar información en formatos reutilizables.', 'd', 'La Ley 19/2013 establece que la información debe ser publicada en formatos reutilizables para facilitar el acceso y la reutilización.'),
('Según el artículo 30 de la Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno, ¿cuál es el plazo máximo para resolver y notificar una reclamación ante el Consejo de Transparencia y Buen Gobierno?', '1 mes.', '2 meses.', '3 meses.', '6 meses.', 'c', 'El artículo 30 de la Ley 19/2013 establece que el plazo máximo para resolver y notificar una reclamación es de 3 meses.'),
('De acuerdo con la Ley 7/1985, de 2 de abril, Reguladora de las Bases del Régimen Local, ¿cuál es el órgano de gobierno de los municipios de gran población?', 'Pleno municipal.', 'Junta de Gobierno Local.', 'Alcaldía.', 'Consejo Social de la Ciudad.', 'b', 'La Junta de Gobierno Local es el órgano de gobierno de los municipios de gran población según la Ley 7/1985.'),
('Conforme a la Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas, ¿cuál es el plazo máximo para dictar y notificar la resolución expresa en un procedimiento administrativo ordinario?', '3 meses.', '6 meses.', '1 año.', 'Indefinido.', 'b', 'La Ley 39/2015 establece un plazo máximo de 6 meses para dictar y notificar la resolución expresa en un procedimiento administrativo ordinario.'),
('Según la Ley Orgánica 3/2007, de 22 de marzo, para la igualdad efectiva de mujeres y hombres, ¿cuál es el órgano encargado de velar por el cumplimiento de las políticas de igualdad de género en España?', 'Consejo de Ministros.', 'Ministerio de Igualdad.', 'Instituto de la Mujer.', 'Comisión de Igualdad del Congreso.', 'c', 'El Instituto de la Mujer es el órgano encargado de velar por el cumplimiento de las políticas de igualdad de género en España.'),
('Según el artículo 20 de la Ley 39/2015, ¿qué recurso administrativo procede contra la inactividad de la Administración?', 'Recurso de alzada.', 'Recurso de reposición.', 'Recurso extraordinario de revisión.', 'Reclamación por responsabilidad patrimonial.', 'a', 'El recurso de alzada procede contra la inactividad de la Administración, según el artículo 20 de la Ley 39/2015.'),
('Según la Ley 29/1998, de 13 de julio, reguladora de la Jurisdicción Contencioso-Administrativa, ¿cuál es el plazo para interponer un recurso contencioso-administrativo contra un acto expreso?', '10 días.', '15 días.', '1 mes.', '2 meses.', 'd', 'El plazo para interponer un recurso contencioso-administrativo contra un acto expreso es de 2 meses según la Ley 29/1998.'),
('De acuerdo con la Ley 9/2017, de 8 de noviembre, de Contratos del Sector Público, ¿cuál es el umbral económico que define los contratos menores?', '5.000 euros.', '15.000 euros.', '40.000 euros.', '60.000 euros.', 'c', 'El umbral económico que define los contratos menores es de 40.000 euros según la Ley 9/2017.'),
('Según el artículo 13 de la Ley 40/2015, de 1 de octubre, de Régimen Jurídico del Sector Público, ¿cuál es el órgano encargado de la coordinación de la política del Gobierno en materia de Función Pública?', 'Consejo de Ministros.', 'Ministerio de Hacienda y Administraciones Públicas.', 'Secretaría de Estado de Función Pública.', 'Comisión de Coordinación de la Función Pública.', 'c', 'La Secretaría de Estado de Función Pública es el órgano encargado de la coordinación de la política del Gobierno en materia de Función Pública.'),
('Según la Ley 7/1985, de 2 de abril, Reguladora de las Bases del Régimen Local, ¿cuál es el plazo máximo para resolver y notificar una reclamación de responsabilidad patrimonial de las Administraciones Públicas?', '3 meses.', '6 meses.', '1 año.', '2 años.', 'c', 'El plazo máximo para resolver y notificar una reclamación de responsabilidad patrimonial es de 1 año según la Ley 7/1985.'),
('Conforme a la Ley 40/2015, de 1 de octubre, de Régimen Jurídico del Sector Público, ¿cuál es el plazo para interponer un recurso de reposición contra un acto administrativo?', '10 días.', '1 mes.', '2 meses.', '3 meses.', 'b', 'El plazo para interponer un recurso de reposición contra un acto administrativo es de 1 mes según la Ley 40/2015.'),
('Según la Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno, ¿cuál es el plazo máximo para resolver una solicitud de acceso a la información pública?', '15 días.', '1 mes.', '2 meses.', '3 meses.', 'b', 'El plazo máximo para resolver una solicitud de acceso a la información pública es de 1 mes según la Ley 19/2013.');

-- tecnicas
USE cuestionario;

INSERT INTO question (pregunta, opcionA, opcionB, opcionC, opcionD, respuesta, teoria) VALUES
('¿Cuál es la normativa que define los requisitos de accesibilidad de los sitios web y aplicaciones móviles de los organismos del sector público?', 'Orden Ministerial 1112/2018, de 7 de septiembre.', 'Ley Orgánica 1112/2018, de 7 de septiembre.', 'Ley 1112/2018, de 7 de septiembre.', 'Real Decreto 1112/2018, de 7 de septiembre.', 'd', 'Real Decreto 1112/2018, de 7 de septiembre, establece los requisitos de accesibilidad de los sitios web y aplicaciones móviles.'),
('¿Cuál de los siguientes es un protocolo de seguridad usado en las comunicaciones HTTP?', 'TLS', 'SSL', 'STARTTLS', 'WPA2', 'a', 'TLS (Transport Layer Security) es el protocolo de seguridad más utilizado para comunicaciones HTTP seguras.'),
('Cuál de los siguientes son los objetos básicos de Kubernetes:', 'Pod, State, Volume, Namespace.', 'Pod, Service, Volume, Namespace.', 'Job, Service, Volume, Namespace.', 'Job, Pod, Volume, Deployment.', 'b', 'Los objetos básicos en Kubernetes incluyen Pod, Service, Volume, y Namespace.'),
('¿Cuál es el prefijo de dirección de Multicast en IPv6?', '::1/128', '224.0.0.0/4', 'FF00::/8', 'FC00::/7', 'c', 'El prefijo de dirección de Multicast en IPv6 es FF00::/8.'),
('¿Cuál de estos equipos de interconexión trabaja a nivel de red (nivel 3 del modelo OSI)?', 'Enrutadores (Routers).', 'Puentes (Bridges).', 'Conmutadores (Switches).', 'Concentradores (Hubs).', 'a', 'Los routers operan en el nivel 3 (capa de red) del modelo OSI.'),
('¿Cuál es el algoritmo para la determinación del camino más corto, dado un vértice origen, hacia el resto de los vértices en un grafo que tiene pesos en cada arista?', 'Algoritmo de Kruskal.', 'Algoritmo de Prim.', 'Algoritmo de Dijkstra.', 'Algoritmo de Floyd-Warshall.', 'c', 'El Algoritmo de Dijkstra se utiliza comúnmente para encontrar el camino más corto en un grafo ponderado.'),
('Con respecto a los estándares PDF, señale que afirmación NO es correcta:', 'PDF/UA Es el estándar global para la accesibilidad de PDF.', 'PDF/A proporciona las especificaciones para crear, ver e imprimir documentos digitales para conservarlos a largo plazo.', 'PDF/E proporciona especificaciones para crear, ver e imprimir documentos utilizados en flujos de trabajo de ingeniería.', 'PDF/I proporciona especificaciones para crear, ver e imprimir páginas finales listas para imprimir o listas para la prensa.', 'd', 'PDF/I no es un estándar reconocido en la industria de los documentos digitales.'),
('¿Qué es WCAG?', 'Unas pautas de accesibilidad de contenidos web promovidas por el W3C.', 'Una librería de Java EE para la creación de aplicaciones web creada por Oracle.', 'Un componente del ecosistema Hadoop para el manejo de Big Data.', 'Un framework javascript especialmente indicado para trabajar con bases de datos no relacionales.', 'a', 'WCAG (Web Content Accessibility Guidelines) son unas pautas de accesibilidad de contenidos web promovidas por el W3C.'),
('Señale la respuesta correcta sobre el modelo CISC:', 'La microprogramación es una característica esencial.', 'Plantea un conjunto reducido de instrucciones para reducir el número de ciclos de reloj de ejecución de cada una de ellas.', 'Implementa las instrucciones directamente en hardware.', 'Está muy extendido en el mercado de procesadores para smartphone y tablets por su bajo consumo y buen rendimiento.', 'a', 'El modelo CISC se caracteriza por el uso de microprogramación en sus instrucciones.'),
('En teoría de grafos, el algoritmo para la determinación del camino más corto, dado un vértice origen, hacia el resto de los vértices en un grafo que tiene pesos en cada arista se denomina:', 'Algoritmo de Kruskal.', 'Algoritmo de Prim.', 'Algoritmo de Dijkstra.', 'Algoritmo de Floyd-Warshall.', 'c', 'El Algoritmo de Dijkstra es ampliamente utilizado para encontrar el camino más corto en un grafo ponderado.'),
('Con respecto a la norma USB indique la respuesta INCORRECTA:', 'USB Type-C es lo mismo que USB 3.1.', 'La diferencia entre USB 3.1 Gen 1 y USB 3.1 Gen 2 se reduce solamente a la velocidad.', 'USB 3.2 permite velocidades de hasta 20 Gbps.', 'Los dispositivos USB 2.0 pueden lograr una velocidad de transferencia máxima hasta de 480 Mbps.', 'a', 'USB Type-C es un tipo de conector, no una especificación de velocidad como USB 3.1.'),
('¿Cuál de las versiones siguientes es la más reciente del sistema operativo macOS?', 'macOS Sierra.', 'macOS Monterey.', 'macOS Big Sur.', 'macOS Ventura.', 'd', 'macOS Ventura es la versión más reciente del sistema operativo de Apple.'),
('Las bases de datos relacionales ofrecen propiedades ACID. Dicho acrónimo se refiere a:', 'Atomicidad, Consistencia, Aislamiento y Durabilidad.', 'Atomicidad, Coherencia, Integridad y Distribución.', 'Disponibilidad, Coherencia, Intensidad y Durabilidad.', 'Atomicidad, Consistencia, Aislamiento y Disponibilidad.', 'a', 'ACID: Atomicidad, Consistencia, Aislamiento y Durabilidad son propiedades fundamentales de las bases de datos transaccionales.'),
('Cuál de los siguientes términos hace referencia a patrones generales de software para asignación de responsabilidades en el diseño orientado a objetos?', 'OOD.', 'GRASP.', 'Booch.', 'Fan-In & Fan-Out.', 'b', 'GRASP (General Responsibility Assignment Software Patterns) es un conjunto de patrones para la asignación de responsabilidades en diseño orientado a objetos.'),
('En SQL, ¿cómo se pueden eliminar los datos en una tabla, pero no la propia definición de la tabla?', 'DROP TABLE.', 'DELETE.', 'REMOVE.', 'ERASE.', 'b', 'La sentencia DELETE elimina los datos dentro de una tabla sin eliminar la tabla misma.'),
('Señale la respuesta INCORRECTA referente al objeto POCO en .NET:', 'Es una estructura de datos de .NET que solo contiene propiedades o campos públicos.', 'Es el acrónimo de Plain Old CLR Object.', 'No hereda de otra clase o implementa una interfaz.', 'Podrá contener miembros como: métodos, eventos y delegados.', 'd', 'Un POCO no debería contener métodos, eventos o delegados para mantenerse como una simple estructura de datos.'),
('¿Cuál de los siguientes NO es un framework para JavaScript?', 'Angular.', 'Bootstrap.', 'React.', 'JDBC.', 'd', 'JDBC no es un framework para JavaScript, es una API para Java en la gestión de bases de datos.'),
('¿Cuál es el objetivo de la técnica de virtualización en informática?', 'Reducir los costos operativos al crear múltiples instancias de sistemas en un solo hardware físico.', 'Mejorar la velocidad de procesamiento de datos mediante la eliminación de hardware innecesario.', 'Eliminar la necesidad de sistemas operativos en entornos empresariales.', 'Aumentar la seguridad informática eliminando vulnerabilidades en el hardware.', 'a', 'La virtualización permite crear múltiples instancias de sistemas en un solo hardware físico, reduciendo costos operativos.'),
('¿Qué significa el concepto de "Data Mining"?', 'La recopilación de datos de múltiples fuentes para su análisis.', 'El proceso de encontrar patrones útiles en grandes volúmenes de datos.', 'El almacenamiento de datos en servidores dedicados.', 'La protección de datos a través de técnicas de encriptación.', 'b', 'El Data Mining es el proceso de encontrar patrones útiles en grandes volúmenes de datos para obtener información valiosa.'),
('¿Cuál es el propósito de un sistema RAID en almacenamiento de datos?', 'Incrementar la velocidad de procesamiento de datos.', 'Proporcionar tolerancia a fallos y mejorar la disponibilidad de datos.', 'Eliminar la necesidad de copias de seguridad periódicas.', 'Mejorar la compatibilidad entre diferentes sistemas operativos.', 'b', 'RAID se utiliza para proporcionar tolerancia a fallos y mejorar la disponibilidad de datos mediante la redundancia.'),
('¿Qué es un "firewall" en términos de seguridad informática?', 'Un dispositivo que elimina virus y malware de un sistema.', 'Un sistema de seguridad que monitorea y controla el tráfico de red entrante y saliente.', 'Un software que permite la ejecución de programas protegidos en entornos controlados.', 'Una técnica de encriptación para proteger datos sensibles.', 'b', 'Un firewall es un sistema de seguridad que monitorea y controla el tráfico de red para proteger contra accesos no autorizados.'),
('¿Cuál de las siguientes opciones describe mejor el concepto de "Big Data"?', 'Datos que son almacenados en dispositivos de almacenamiento masivo.', 'Conjuntos de datos que son tan grandes o complejos que las aplicaciones tradicionales de procesamiento de datos no pueden manejarlos.', 'Una pequeña cantidad de datos utilizados para pruebas de sistemas.', 'Datos que son específicamente protegidos por leyes internacionales.', 'b', 'Big Data se refiere a conjuntos de datos extremadamente grandes o complejos que requieren métodos avanzados para su análisis.'),
('¿Qué es la tecnología "blockchain"?', 'Una red privada de computadoras para compartir archivos.', 'Un sistema de bases de datos centralizadas utilizadas por bancos.', 'Una estructura de datos que permite mantener un registro de transacciones de manera segura y descentralizada.', 'Un tipo de antivirus avanzado.', 'c', 'La tecnología blockchain es una estructura de datos que permite registrar transacciones de manera segura y descentralizada.'),
('En redes de computadoras, ¿qué significa el término "latencia"?', 'La velocidad de transferencia de datos en una red.', 'El tiempo que tarda un paquete de datos en ir desde el origen hasta el destino.', 'La cantidad de datos que se pueden transferir en un período de tiempo determinado.', 'La interrupción temporal de servicios de red.', 'b', 'La latencia es el tiempo que tarda un paquete de datos en viajar desde el origen hasta el destino en una red.'),
('¿Qué es un "servidor proxy"?', 'Un dispositivo de red que permite la comunicación entre diferentes subredes.', 'Un servidor que actúa como intermediario para las solicitudes de clientes que buscan recursos en otros servidores.', 'Un software que asegura que todos los datos en una red sean encriptados.', 'Un tipo de firewall avanzado para proteger contra ataques DDoS.', 'b', 'Un servidor proxy actúa como intermediario entre el cliente y el servidor de destino, facilitando o filtrando las solicitudes.'),
('¿Cuál de las siguientes tecnologías es fundamental para el funcionamiento de las redes privadas virtuales (VPN)?', 'HTML.', 'TLS/SSL.', 'HTTP.', 'DNS.', 'b', 'TLS/SSL son protocolos fundamentales para cifrar y asegurar las conexiones en redes privadas virtuales (VPN).'),
('¿Qué significa el concepto de "Internet de las Cosas (IoT)"?', 'El uso de internet para compartir archivos y documentos.', 'La conexión de dispositivos físicos a internet para que puedan recopilar e intercambiar datos.', 'Una red de computadoras dedicadas exclusivamente a la transmisión de datos de voz.', 'Un sistema de almacenamiento masivo de datos en la nube.', 'b', 'El Internet de las Cosas (IoT) se refiere a la conexión de dispositivos físicos a internet para recopilar e intercambiar datos.'),
('¿Cuál es la función principal de un sistema operativo?', 'Proporcionar una interfaz entre el usuario y el hardware.', 'Eliminar virus y malware del sistema.', 'Compilar y ejecutar programas de software.', 'Proporcionar seguridad y protección a los datos.', 'a', 'El sistema operativo proporciona una interfaz entre el usuario y el hardware, gestionando los recursos y las aplicaciones del sistema.'),
('En desarrollo de software, ¿qué es un "repositorio"?', 'Un lugar donde se almacenan los datos de usuarios de una aplicación.', 'Una colección de archivos de código fuente gestionados y almacenados para su colaboración y versionado.', 'Un software que se encarga de compilar el código fuente.', 'Una herramienta de análisis de la calidad del código.', 'b', 'Un repositorio es una colección de archivos de código fuente gestionados y almacenados para su colaboración y versionado.'),
('¿Qué es el "Machine Learning"?', 'El proceso de programación de máquinas para realizar tareas repetitivas.', 'Un campo de la inteligencia artificial que permite a los sistemas aprender y mejorar automáticamente a partir de la experiencia.', 'Un método para construir hardware más eficiente.', 'Una técnica de organización de bases de datos.', 'b', 'El Machine Learning es un campo de la inteligencia artificial que permite a los sistemas aprender y mejorar automáticamente a partir de la experiencia.');





